#!/usr/bin/env bash
# Create (or adopt) the Cloudflare tunnel that fronts the three hostnames, write the
# ingress config the tunnel container mounts, and point DNS at it. Idempotent.
#
# Run this on the machine that will RUN the tunnel. A tunnel's credentials live only on the
# machine that created it, so creating it here and running it elsewhere does not work; the
# script checks for that and says so rather than half-applying.
set -euo pipefail
cd "$(dirname "$0")/.."
# shellcheck source=scripts/lib.sh
. ./scripts/lib.sh
load_env

: "${TUNNEL_NAME:?set TUNNEL_NAME in .env.deploy}"
: "${APP_HOST:?set APP_HOST in .env.deploy}"
: "${CONVEX_CLOUD_ORIGIN:?set CONVEX_CLOUD_ORIGIN in .env.deploy}"
: "${CONVEX_SITE_ORIGIN:?set CONVEX_SITE_ORIGIN in .env.deploy}"

command -v cloudflared >/dev/null || {
  cat >&2 <<'MSG'
cloudflared is not installed. On a Debian or Ubuntu box:
  sudo curl -fsSL -o /usr/local/bin/cloudflared \
    https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
  sudo chmod +x /usr/local/bin/cloudflared
MSG
  exit 1
}
command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 1; }

# Accepts https://host, http://host, or a bare host, with or without a path.
host_of() {
  local v=${1#http://}
  v=${v#https://}
  echo "${v%%/*}"
}
APP=$(host_of "$APP_HOST")
API_HOST=$(host_of "$CONVEX_CLOUD_ORIGIN")
SITE_HOST=$(host_of "$CONVEX_SITE_ORIGIN")
for h in "$APP" "$API_HOST" "$SITE_HOST"; do
  case "$h" in
    *.*) ;;
    *) echo "'$h' does not look like a hostname; check APP_HOST and the two origins" >&2; exit 1 ;;
  esac
done

# 1. Authorise once. cert.pem is what lets us create tunnels and DNS records.
if [ ! -f "$HOME/.cloudflared/cert.pem" ]; then
  echo "Authorising with Cloudflare; follow the URL it prints."
  cloudflared tunnel login
fi

# 2. Find the tunnel, or make one. A single JSON parse, with the name passed as an argument
#    rather than interpolated, and no output when it simply does not exist yet.
tunnel_id() {
  cloudflared tunnel list --output json 2>/dev/null | python3 -c '
import sys, json
name = sys.argv[1]
try:
    tunnels = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for t in tunnels:
    if t.get("name") == name:
        print(t.get("id", ""))
        break
' "$TUNNEL_NAME"
}

TUNNEL_ID=$(tunnel_id)
if [ -n "$TUNNEL_ID" ]; then
  echo "adopting existing tunnel '$TUNNEL_NAME' ($TUNNEL_ID)"
else
  echo "creating tunnel '$TUNNEL_NAME'"
  cloudflared tunnel create "$TUNNEL_NAME"
  TUNNEL_ID=$(tunnel_id)
  [ -n "$TUNNEL_ID" ] || { echo "tunnel was created but could not be found again" >&2; exit 1; }
  echo "tunnel id: $TUNNEL_ID"
fi

# 3. Credentials must be here BEFORE anything is changed at Cloudflare. Repointing DNS and
#    then failing on a missing file is how a working setup gets left in pieces.
CRED="$HOME/.cloudflared/$TUNNEL_ID.json"
if [ ! -f "$CRED" ]; then
  cat >&2 <<MSG
Tunnel '$TUNNEL_NAME' ($TUNNEL_ID) exists in your Cloudflare account, but its credentials
are not on this machine: $CRED is missing. A tunnel's credentials are written only where it
was created, so it cannot be run from here as things stand.

Pick one:
  1. Run it from the machine that created it, or copy that machine's
     ~/.cloudflared/$TUNNEL_ID.json to the same path here.
  2. Delete the tunnel and let this script make a fresh one:
       cloudflared tunnel delete $TUNNEL_ID
     Safe when it has no active connections, which you can check with:
       cloudflared tunnel list

Nothing has been changed.
MSG
  exit 1
fi

# 4. Local config. Stale credentials from an earlier tunnel are cleared out, so the
#    directory can never offer the container a file the config does not name.
mkdir -p cloudflared
find cloudflared -maxdepth 1 -name '*.json' ! -name "$TUNNEL_ID.json" -delete
cp "$CRED" "cloudflared/$TUNNEL_ID.json"
chmod 600 "cloudflared/$TUNNEL_ID.json"

# The image runs as uid 65532 and would be locked out of a 0600 file owned by this user.
# Pin the container to the owner rather than making the credentials world readable.
put_env TUNNEL_USER "$(id -u):$(id -g)"
echo "tunnel container will run as $(id -u):$(id -g)"

cat > cloudflared/config.yml <<EOF
# Generated by scripts/tunnel.sh. Edit .env.deploy and re-run rather than editing here.
tunnel: $TUNNEL_ID
credentials-file: /etc/cloudflared/$TUNNEL_ID.json

ingress:
  - hostname: $APP
    service: http://web:80
  - hostname: $API_HOST
    service: http://backend:3210
  - hostname: $SITE_HOST
    service: http://backend:3211
  - service: http_status:404
EOF
echo "wrote cloudflared/config.yml"

# 5. DNS last, once everything local is known good. --overwrite-dns takes a record over,
#    so say which ones and where they point today.
echo
echo "Pointing DNS at this tunnel. Any existing record for these names is replaced:"
for h in "$APP" "$API_HOST" "$SITE_HOST"; do
  current=$(getent hosts "$h" 2>/dev/null | awk '{printf "%s ", $1}')
  echo "  $h ${current:+(currently $current)}"
done
for h in "$APP" "$API_HOST" "$SITE_HOST"; do
  cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$h"
done

cat <<EOF

  $APP        -> web
  $API_HOST   -> backend api
  $SITE_HOST  -> backend http actions and auth

Start it with: ./scripts/deploy.sh
EOF
