import type { IconType } from "react-icons";
import {
  LuArrowDown,
  LuArrowLeftRight,
  LuArrowRight,
  LuBan,
  LuBomb,
  LuCloudFog,
  LuEyeOff,
  LuFlipHorizontal2,
  LuMusic,
  LuSwords,
  LuUsers,
  LuVote,
  LuBookOpen,
  LuEye,
  LuFlag,
  LuFlame,
  LuFlipVertical2,
  LuGift,
  LuLayers,
  LuLock,
  LuMegaphone,
  LuRotateCw,
  LuShield,
  LuShuffle,
  LuSparkles,
  LuStore,
  LuWandSparkles,
  LuZap,
} from "react-icons/lu";
import type { Twist } from "@/engine";

/** One stable, recognizable mark per Party twist, shared by the table and the Rules page. */
export const PARTY_TWIST_ICONS: Record<Twist, IconType> = {
  desce: LuArrowDown,
  golden: LuSparkles,
  lastTrick: LuFlag,
  blankPays: LuGift,
  noTrump: LuBan,
  pass: LuArrowRight,
  lightning: LuZap,
  asDealt: LuLock,
  swap: LuShuffle,
  guardian: LuShield,
  freeForAll: LuFlame,
  wildRank: LuWandSparkles,
  carousel: LuRotateCw,
  market: LuStore,
  dummy: LuLayers,
  faceUp: LuEye,
  inverted: LuFlipVertical2,
  team: LuUsers,
  nemesis: LuSwords,
  mirror: LuFlipHorizontal2,
  musicalTricks: LuMusic,
  robinHood: LuArrowLeftRight,
  markedCard: LuBomb,
  fog: LuCloudFog,
  blindLead: LuEyeOff,
  voteTrump: LuVote,
  // These two are implemented but currently outside the draw pool.
  openHands: LuBookOpen,
  allIn: LuMegaphone,
};
